COLUMNS = ['collectionId', 'images', 'system_id', 'accession_no', 'accession_date', 'department', 'other_id',
           'other_id_type', 'public_access_text', 'credit_line', 'collection', 'provenance_details',
           'provenance_place', 'provenance_date', 'name', 'description', 'other_name', 'other_name_type',
           'cultural_origin', 'taxonomic_classification', 'physical_description', 'object_type',
           'documentation',
           'assoc_event', 'assoc_notes', 'assoc_place', 'assoc_role', 'assoc_date', 'related_objects', 'role',
           'date', 'place', 'technique', 'style', 'measurement_description', 'measurements', 'media_materials',
           'media_materials_description', 'media_materials_notes', 'field_collection_place',
           'field_collection_site', 'field_collection_site_description', 'field_collection_method',
           'field_collection_date', 'external_file_name', 'prod_notes', 'subject_category', 'web_address',
           'level_current_record', 'is_part_of', 'member_object', 'period', 'type_status', 'restriction', 'sex',
           'display_location', 'scientific_name', 'taxon_rank', 'genus_species_authority', 'document_pg_number',
           'field_collection_notes', 'field_collection_datum', 'field_collection_latitude_precision',
           'field_collection_latitude_from', 'field_collection_longitude_precision',
           'field_collection_longitude_from', 'locality_description', 'specimen_category', 'storage_method',
           'stratigraphy', 'common_name', 'site_altitude_from', 'site_depth_from', 'site_longitude_to',
           'site_longitude', 'site_longitude_precision', 'site_latitude', 'site_latitude_precision',
           'site_habitat_notes', 'site_collection_method', 'site_collection_date', 'site_region', 'site_datum',
           'last_update', 'qualifier', 'collection_area', 'type_title', 'tags', 'display_room', 'language',
           'language_description', 'copyright_notes', 'isbn_issn', 'content', 'contributor_publisher',
           'serial_holdings', 'collection_type', 'volume_number', 'prod_date_notes', 'subject_notes',
           'secondary_production_role', 'edition', 'related_object_notes', 'signature_marks', 'signature_type',
           'related_objects_notes', 'order', 'superfamily', 'family', 'genus', 'subname', 'species',
           'te_reo_name',
           'site_description']

LAST_PAGE = 137